# font_family IosevkaTerm Nerd Font Mono
# font_family JetBrainsMono NF
font_family Lilex
font_size 25

background_opacity 0.85

window_padding_width 10

cursor #FFD700


# Reload config with just F5
map f5 load_config_file
