#
# prezto - mimic the default prezto prompt (sorin) - Tokyo Night Edition
#

add_newline = true

# A minimal left prompt
format = """$username$localip / $directory$git_branch$git_status \n$character"""

# move the rest of the prompt to the right
right_format = """$status"""

[gcloud]
format = '{gcp::[$account(\($project\))]($style)}'
style = "bold #7aa2f7"

[localip]
ssh_only = false
format = '[{$localipv4}](bold #565f89)'
disabled = false

[kubernetes]
disabled = false
format = '{[k8s:](#565f89)[$context-$namespace]($style)}'
style = "bold #bb9af7"

[username]
format = "{[$user]($style)}"
show_always = true
style_root = "bold #f7768e"
style_user = "#e0af68"
disabled = false

[character]
success_symbol = "[❱](#9ece6a)" # Tokyo Green
error_symbol = "[❱](#f7768e)"   # Tokyo Red
vicmd_symbol = "[❰](#7dcfff)"   # Tokyo Cyan

[git_branch]
format = '[{](bold #acb0d0)[git:](#565f89)[$branch]($style)'
style = 'bold underline #e0af68'

[git_status]
format = ' $all_status$ahead_behind[}](bold #acb0d0)'

# Movement: Up/Down is standard, but these feel more "dynamic"
ahead = '[⇡](#bb9af7)'   # Arrow pointing up to the cloud
behind = '[⇣](#bb9af7)'  # Arrow pulling down from the cloud

# The Index: Staged vs Modified vs Untracked
staged = '[ ](#9ece6a)'    # Plus inside a square (addition to index)
modified = '[ ](#f7768e)'  # Circle with a dot (change in existing file)
untracked = '[](bold #7aa2f7)' # Question mark (Git doesn't know this file)

# Destructive/Changes
deleted = '[ ](#f7768e)'   # X mark (removal)
renamed = '[󰁯 ](#bb9af7)'   # Arrow curving right (moved/renamed)

# Special States
stashed = '[ ](#7dcfff)'    # A package/box (hidden away for later)
conflicted = '[ ](#e0af68)' # Warning sign or double-exclamation
diverged = '[󰹹 ](#bb9af7)'   # Parallel lines moving apart (⇕ is also good, but this is cleaner)

# Status
up_to_date = '[✓](italic #565f89)' # A simple checkmark is more semantic than "nil"

[directory]
style = "bold #ff9e64" # Tokyo Orange
format = '[\[](bold #acb0d0) [pwd:](#565f89) [$path]($style) [\]](bold #acb0d0)[$read_only]($read_only_style) '
truncation_length = 2

[cmd_duration]
format = '[$duration]($style) '
style = "bold #cfc9c2"

[status]
disabled = false
symbol = '✘ '
style = "bold #f7768e"

[python]
format = '[(\($virtualenv\) )]($style)'
style = '#9ece6a'
